jobs:
  odoo:
    machine: true
    steps:
       - checkout

       - run:
          name: Login to Quay.io
          command: docker login quay.io -u "${QUAY_USER}" -p "${QUAY_TOKEN}"

       - run:
          name: Build -- Init Database
          command: docker-compose run --rm odoo odoo --stop-after-init -i main

       - run:
          name: Setup Log Folder For Reports
          command: sudo mkdir -p ./log && sudo chmod 777 ./log

       - run:
          name: Run Test
          command: docker-compose run --rm odoo run_pytest.sh

       - run:
          name: Codacy Coverage
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l python -r .log/coverage.xml

       - store_test_results:
          path: ./log

  auto-tag:
    machine: true
    steps:
      - checkout
      - run:
          name: Get nws
          command: |
            curl -L $NWS_BIN_LOCATION > ./nws
            chmod +x ./nws
      - run:
          name: Set tag
          command: |
            ./nws circleci create-tag -t odoo-base

workflows:
  version: 2
  basic-odoo-test:
    jobs:
      - odoo:
          context: quay.io
      - auto-tag:
          context: nws
          requires:
            - odoo
          filters:
            branches:
              only: /^1\d\.0/
